version: "3.3"
services:
    tsuserver:
        build: .
        image: tsuservercc
        ports:
            - 27016:27016
            - 50001:50001
        volumes:
            - ./storage:/tsuserver3cc-musicautoscan/OLEAO-ServerCC/storage
            - ./logs:/tsuserver3cc-musicautoscan/OLEAO-ServerCC/logs
            - ./config:/tsuserver3cc-musicautoscan/OLEAO-ServerCC/config
            - ./base/sounds/music:/tsuserver3cc-musicautoscan/OLEAO-ServerCC/base/sounds/music
            - ffmpeg:/opt/ffmpeg-4.4-amd64-static/ffmpeg
            - ffprobe:/opt/ffmpeg-4.4-amd64-static/ffprobe
        restart: unless-stopped

