- area: Lobby
  background: PLvsPWCourtroomLabyrinthiaFire
  bglock: true
  evidence_mod: Mods
  locking_allowed: false
  iniswap_allowed: false
  shouts_allowed: false
  showname_changes_allowed: true
- area: User Hub
  background: DGSCourtroomEnglishAnim
  abbreviation: UHUB
  bglock: true
  evidence_mod: Mods
  locking_allowed: false
  iniswap_allowed: true
  shouts_allowed: false
  showname_changes_allowed: true
  is_hub: true
  hubtype: user
- area: Courtroom 1
  background: AACourtHD
  bglock: false
  evidence_mod: Mods
  locking_allowed: true
  iniswap_allowed: true
  shouts_allowed: true
  showname_changes_allowed: true
- area: Courtroom 2
  background: AJCourtHD
  bglock: false
  evidence_mod: Mods
  locking_allowed: true
  iniswap_allowed: true
  shouts_allowed: true
  showname_changes_allowed: true
- area: Courtroom 3
  background: AJCourtHD
  bglock: false
  evidence_mod: Mods
  locking_allowed: true
  iniswap_allowed: true
  shouts_allowed: true
  showname_changes_allowed: true
- area: Courtroom 4
  background: DDCourtroomHD
  bglock: false
  evidence_mod: Mods
  locking_allowed: true
  iniswap_allowed: true
  shouts_allowed: true
  showname_changes_allowed: true
- area: Courtroom 5
  background: DGSCourtroomEnglishAnim
  bglock: false
  evidence_mod: Mods
  locking_allowed: true
  iniswap_allowed: true
  shouts_allowed: true
  showname_changes_allowed: true
- area: Ministry of Justice
  background: DGS2BarokOffice
  bglock: false
  evidence_mod: Mods
  locking_allowed: true
  iniswap_allowed: true
  shouts_allowed: true
  showname_changes_allowed: true