- Phoenix
- PhoenixPLvsPW
- PhoenixSOJSD
- PhoenixAAI
- Apollo 
- ApolloDD
- ApolloSOJ
- AthenaSOJ
- Athena2D
- Mia
- Grossberg 
- Diego
- Yew
- Gregory 
- GregoryAAI
- Raymond
- Ryuunosuke
- RyuunosukeBadgeless
- Asougi
- Ryuutarou
- Hugh Def
- Payne
- Gaspen
- Auchi
- Payne3D
- Payne Train
- Miles
- MilesDD
- EdgeworthSOJ
- Manfred
- Franziska
- Godot
- Klavier
- KlavierDD
- Portsman
- Sebastian
- Blaise
- LaytonPLvsPW
- Zacharias
- Darklaw
- Blackquill
- BlackquillSOJ 
- Nahyuta
- Inga
- Garan
- AsougiPro
- Barok
- Disciple
- Flynch
- ApolloPro
- Betty Pro Famme
- Trucy Pro
- Hawk
- Neil
- Mysterious Stranger
- Zero
- Maya
- MayaSOJ
- MayaPLvsAA
- Ema
- Maggey 
- Kristoph
- HoboPhoenix
- HoboTrucy
- Trucy
- Trucy Young
- Byrne
- Kay
- Susato
- Judge
- JudgeBro
- JudgeDGS-ENG
- JudgeDGS-JAP
- Seishirou
- Stronghart
- JudgeKhura'in
- JudgeSOJ
- Rayfa
- Courtney
- Hemlock
- Abigail
- Anna
- Bongo
- Burley
- Vilen
- Richard
- Shiv
- Parker
- Altamont
- Evie
- Charles
- Gumshoe
- Marshall 
- Atmey
- EmaSOJSD
- Buddy
- Badd 
- Lang
- Bobby
- Herlock
- Tobias
- Gina
- Snow
- Arme
- Cabanela 
- Butz 
- Sahwit
- April
- Bellboy
- White 
- Will
- Oldbag
- Cody
- Penny
- Sal
- Vasquez 
- Lotta 
- Yanni
- Polly
- Lana
- Angel 
- Gant
- Meekins
- Wellington
- Grey
- Ini
- Pearl
- Morgan
- Hotti 
- Max
- Moe
- Ben
- Regina
- Acro 
- Matt
- deKiller
- Adrian
- Feenie
- Dahlia
- Ron
- Desiree
- Kudo
- Armstrong
- Furio
- Viola
- Lisa 
- Fawles
- Iris
- Elise
- Olga
- Zak
- Wocky Kitaki
- Wesley
- Alita
- Guy
- Plum
- Winfred
- Machi
- LeTouse
- Lamiroir
- Daryan
- Valant
- Vera 
- Vera Young
- Drew
- Spark
- Rhoda Teneiro
- Zinc
- Cammy
- Ernest 
- Lance
- Shih-na
- Lauren
- WillP AAI
- Colias
- Alba
- Huang
- Nicole
- Knightley
- Simon
- Elbird
- Patricia
- Dogen
- Jeffrey
- Gustavia
- Katherine Hall
- Delicia
- Bonnie and Karin
- John Marsh
- Espella
- Smiles
- Cracker
- Shakey
- Ridelle
- Jean
- Juniper
- Tonate
- Tenma
- Filch
- Jinxie
- Florent 
- Means
- Newman
- Hugh
- Scuttlebutt
- Starbuck 
- Cosmos
- Aura 
- Ponco
- Clonco
- Orla
- Buckler
- Deplume
- Crab
- Ahlbi
- Amara
- Andistandhin
- Bailiff
- TrucySOJ
- Betty
- Bonny
- Retinz
- Datz
- Geiru
- Uendo
- Atishon
- PearlSOJ
- Tahrust
- Dhurke
- Ellen
- ButzSOJ
- Armie
- Sorin
- Pierce
- Bucky
- Hosonaga
- Jezaille
- Mikotoba
- Yuujin Mikotoba Suit
- Nikolina
- Strongenov 
- McGilded
- Beppo
- Furst
- Iris Wilson 
- Bruce
- Joan
- Garrideb
- Maurice
- Souseki
- Pop
- Nash
- Ringo
- Graydon
- Rei
- William
- Patrick
- Rola
- Rumba
- Tusspells
- Drebber
- Adron
- Daley
- Menimemo
- Maria
- Sithe 
- Nosa
- Venus
- Gossip
- Gotts
- Olive
- Harebrayne
- Sailor 
- BailiffDGS
- Narrator
- NarratorDGS
- Psychelocks
- Mood_Matrix
- The Typewriter
- Layton
- Luke
- Alfendi
- Makepeace
- Lucy
- Anton
- Chelmey
- Claire
- Clive
- Descole
- Don
- Emmy
- Flora
- Grosky
- Dimitri
- Barton
- Riddleton
- Puzzlette
- Katrielle Layton
- Sissel
- Lynne
- iniswap1
- iniswap2
- iniswap3
- iniswap4
- iniswap5
- iniswap6
- iniswap7
- iniswap8
- iniswap9
- iniswap10
- iniswap11
- iniswap12
- iniswap13
- iniswap14
- iniswap15
- iniswap16
- iniswap17
- iniswap18
- iniswap19
- iniswap20