- hdid: 
  ipid: 
  name: Pina
  status: admin
- hdid: 
  ipid: 
  name: Fruitbat
  status: admin
- hdid: 
  ipid: 
  name: Steel
  status: admin
- hdid: 
  ipid:
  name: HolyMan
  status: admin
- hdid: 
  ipid: 
  name: XYZ
  status: admin